### ISSUE TITLE
Issue sobre Anexo de toxicidad por sanchovera@hotmail.com

### ISSUE THREAD

**Issue by matiasalbacetti** [Larrata/DocumentosOficiales#57]
Pienso que es necesario analizar el anexo sobre toxicidad y implementarlo como articulo. 

Enviado desde mi iPhone

**Comment by matiasalbacetti** [comment]
Comparto. De alguna forma debe ser modificado para que su aplicación sea más ágil.

**Comment by Larrata** [comment]
Se implementó el anexo
