### ISSUE TITLE
Modificación articulo Nro.2

### ISSUE THREAD

**Issue by NicolasRamis** [Larrata/DocumentosOficiales#61]
Debido a la reciente advertencia al agente Franco Mendez quien subió un recuerdo grupal en el cual se encontraba Jeremias Chavez (actualmente censurado) quería pedir evalúen modificar el articulo correspondiente o agregar una excepcion.
Es muy engorroso tener que editar una imagen en la cual se encuentre dicha persona por lo que los agentes podrían decidir no subir el contenido lo cual a mi parecer haría mas pobre a nuestro grupo.
Deberían modificar lo necesario para que las imagenes donde aparezca Jeremias Chavez no sean censuradas.

Desde ya muchas gracias.

Nicolas Martin Ramis - El Gordo - Camionero virtual.

**Comment by matiasalbacetti** [comment]
Se resuelve agregar la excepción a la regla.
#62
