### ISSUE TITLE
Control de toxicidad - Provocaciones

### ISSUE THREAD

**Issue by NicolasRamis** [Larrata/DocumentosOficiales#67]
Agradeceré evalúen agregar al control de toxicidad las provocaciones ya que en mas de una oportunidad fueron disparadores de toxicidades.

Saludos

**Comment by matiasalbacetti** [comment]
Atribuir la emisión de toxicidad a provocaciones de terceros se asemeja a atribuir una violación a la vestimenta que llevaba la víctima.

Para que las eventuales provocaciones sean pasibles de sanción, será una condición necesaria que éstas también estén dotadas de toxicidad. Siendo tóxicas per se, estas acciones serán tratadas con el mismo criterio que cualquier otra. 

Teniendo en cuenta lo mencionado, considero innecesario modificar el reglamento y recomiendo que si se detectan provocaciones con contenido tóxico, las mismas sean reportadas para su eficaz trato.
